### PR TITLE
Nl 80 login style fixes christopher

### LINKED ISSUE #80: login/signup buttons drop shadows
check the design of the login/signup buttons with those on github
Screen Shot 2022-05-28 at 4 42 07 PM
Screen Shot 2022-05-28 at 4 42 22 PM

### LINKED ISSUE #89: Login page proportions
the login page proportions are off, the text on the left is stretched

Screen Shot 2022-05-28 at 5 02 44 PM

### PR DESCRIPTION
**Pull request by cfellowes**
small tweaks to login page, buttons should now all have on-hover effects to make them feel more reactive. Adjusted page proportions slightly based on professor's feedback.

### CODE REVIEW

**Review by DustinLin — COMMENTED** [review]
The icons for the user and password still seen stretched (but everything else seems good)

**Comment by DustinLin** [comment]
Screen Shot 2022-06-03 at 8 52 33 PM

for reference

**Comment by DustinLin** [comment]
Screen Shot 2022-06-03 at 8 53 06 PM

also if the browser isn't full screen, the "---sign in with email---" tag gets cut off and wraps around

**Comment by DustinLin** [comment]
Other's can't replicate

**Comment by Rick10101221** [comment]
Closes #80 #89

**Comment by cfellowes** [comment]
Closes #77

**Pull request merged**
