### PR TITLE
General Styling/Logic/Organization Changes + Bug Fixes 

### LINKED ISSUE #130: Cursor Pointer Around Repository
## Name and Email
  - Name: Rickesh Khilnani
  - Email: rickeshkhilnani@gmail.com

## Complexity of Issue (Scale from 1-5)
  - 2
  
## Issue Description
  - Add cursor: pointer in appropriate places

### LINKED ISSUE #131: Constants to Uppercase Around Repository
## Name and Email
  - Name: Rickesh Khilnani
  - Email: rickeshkhilnani@gmail.com

## Complexity of Issue (Scale from 1-5)
  - 1
  
## Issue Description
  - Make constants uppercase by convention

### PR DESCRIPTION
**Pull request by Rick10101221**
Fix calendar highlight to not highlight fake days
Organize CSS
Organize Login JS
Fix CSS for daily overview save button to match the one on weekly overview
Make notes on daily overview larger
Organize Calendar JS
Add comments to Calendar JS for clarity
Organize CSS properties in selectors
Remove unnecessary ESLint disables
Constants at top of files to upper case
[Fix photo album being pushed down on DailyJS](https://cse112-sp22-group9.slack.com/archives/C03H9S0D0Q4/p1654712895322719)

See commit messages (and amends) for further details

Closes #130 #131 

MUST MERGE #137

### CODE REVIEW

**Comment by Rick10101221** [comment]
UNMERGABLE. HAVE NOT COMPLETED #131

**Comment by Rick10101221** [comment]
Please check PR preview links before merging to make sure nothing has broke

**Comment by Yenyun035** [comment]
image
I think it's a bit hard to see

**Comment by Rick10101221** [comment]
Reverted the button colors [mentioned here](https://github.com/CSE112-sp22-group9/cse112-sp22-group9/pull/140#issuecomment-1150484913)

**Review by DustinLin — COMMENTED** [review]
Cleaned up code, named constants variables to all-caps

**Pull request merged**
