### PR TITLE
Nl 23 frontend update chris sophia

### PR DESCRIPTION
**Pull request by cfellowes**
HTML/CSS for weekly preview finished, just need to update calendar/settings buttons and render from backend.

### CODE REVIEW

**Comment by DustinLin** [comment]
ESLint errors are already resolved in the development branch

**Comment by DustinLin** [comment]
large comments are for database calls that will be reimplemented

**Comment by DustinLin** [comment]
I'm working on resolving merge conflicts and eslint errors, there are 2 unused functions in Calendar.js, can see my comments

**Comment by DustinLin** [comment]
Also why are the Weeklyoverview pages inside the Login directory?

**Comment by cfellowes** [comment]
> Also why are the Weeklyoverview pages inside the Login directory?

**Pull request merged**
